### ISSUE TITLE
Android 设置扫描区域后，水平方向移出扫描框，任然能够识别二维码

### ISSUE THREAD

**Issue by sabrechen** [HMS-Core/hms-scan-demo#10]
如何设置只在扫描框内识别二维码？

**Comment by Mike-mei** [comment]
1.请检查手机上的HmsCore是否升级到应用市场最新版本。
2.扫描区域和实际看到的是不完全一致的，为了防止卡在边界扫不出来的情况，设置的扫描区域比扫描框稍大一点

**Comment by sabrechen** [comment]
我使用的SDK版本：com.huawei.hms:scanplus:1.2.2.300
我的问题，不是卡在边界无法扫描，而是水平方向的扫描区域与我设置的区域不匹配，超过了我设置的区域，导致移出我设置的扫描区域依然能够识别出二维码结果

**Comment by Mike-mei** [comment]
目前由于水平方向本身较小，水平方向未作限制，默认全屏支持。
