### ISSUE TITLE
能否提供暂停扫描,恢复扫描及设置不自动放大码的方法

### ISSUE THREAD

**Issue by singlenoah** [HMS-Core/hms-scan-demo#12]
1 在有些场景中是一直在扫码页面进行业务操作的,所以希望提供暂停扫码及继续开始扫码功能
2 在连续扫描的时候焦距会不断调整,体验不是很少,所以希望能提供自由设置是否放大码的功能

**Comment by HMS-ScanKit** [comment]
暂停扫码：remoteview.pauseContinuouslyScan()
恢复扫码：resumeContinuouslyScan()
是否支持自动放大暂时不支持定制。
