### ISSUE TITLE
能否提供fragment能使用的Default View Mode方式？

### ISSUE THREAD

**Issue by xiang23** [HMS-Core/hms-scan-demo#17]
现在ScanUtil.startScan的方式fragment的onActivityResult是无法收到回调的

**Comment by Mike-mei** [comment]
你好，考虑到添加fragment要引入 android support包，会让体积变大，所以目前不提供fragment能使用的Default View Mode方式。需要在Activity触发fragment的onactivityResult，即可收到回调。
