### ISSUE TITLE
草料二维码生成器生成的二维码无法识别出来

### ISSUE THREAD

**Issue by ziyouxiaozi** [HMS-Core/hms-scan-demo#20]
是有一些无法识别出来，比如内容是几个中文字或者数字时识别不出来？

**Comment by ziyouxiaozi** [comment]
是有一些无法识别出来，比如内容是几个中文字或者数字时识别不出来？

**Comment by HMS-ScanKit** [comment]
您好，麻烦提供失败的用例，这边会进行跟进分析

**Comment by ziyouxiaozi** [comment]
你可以试试这个二维码，识别出来的概率很低。用华为的emui4.0.3系统的PLK-AL10手机无法识别出来？
![二维码图片_4月28日14时20分02秒](https://user-images.githubusercontent.com/2511739/116355846-053fe400-a82d-11eb-8778-9e64dedbe7fb.png)

**Comment by HMS-ScanKit** [comment]
您好，这边对用例进行了验证，未发现异常

**Comment by 32R34L** [comment]
其实不是全屏扫码，把二维码置于扫码界面中和下就能识别。
