### ISSUE TITLE
setPhotoMode 不起作用

### ISSUE THREAD

**Issue by Marx-Hong** [HMS-Core/hms-scan-demo#22]
setPhotoMode 方法，不论传参true 或者false 扫码页面的本地图片按钮都显示

**Comment by HMS-ScanKit** [comment]
您好，setPhotoMode的意思是:是否采用图片解码模式

**Comment by Marx-Hong** [comment]
能否有方法关闭扫码本地图片的功能，封装程度太高，看demo也没用适配30
