### ISSUE TITLE
使用fragment 加载自定义View界面 报错

### ISSUE THREAD

**Issue by HuaZaiWuDi** [HMS-Core/hms-scan-demo#23]
`
    private val scanView: RemoteView by lazy { RemoteView.Builder().setIsCustomView(true).setContext(_mActivity).setFormat(HmsScan.QRCODE_SCAN_TYPE).build() }

    private fun initScanner() {
        //1. Obtain the screen density to calculate the viewfinder's rectangle.
        val dm = resources.displayMetrics
        val density = dm.density
        //2. Obtain the screen size.
        //2. Obtain the screen size.
        val mScreenWidth = resources.displayMetrics.widthPixels
        val mScreenHeight = resources.displayMetrics.heightPixels

        val scanFrameSize = (260 * density).toInt()

        //3. Calculate the viewfinder's rectangle, which in the middle of the layout.
        //Set the scanning area. (Optional. Rect can be null. If no settings are specified, it will be located in the middle of the layout.)
        val rect = Rect()
        rect.left = mScreenWidth / 2 - scanFrameSize / 2
        rect.right = mScreenWidth / 2 + scanFrameSize / 2
        rect.top = mScreenHeight / 2 - scanFrameSize / 2
        rect.bottom = mScreenHeight / 2 + scanFrameSize / 2

        val params = FrameLayout.LayoutParams(LinearLayout.LayoutParams.MATCH_PARENT, LinearLayout.LayoutParams.MATCH_PARENT)
        scan_content_layout?.addView(scanView, params)

        scanView?.setOnResultCallback(mScannerCallBack)
        scanView?.setOnErrorCallback {
            d("扫描失败：", it)
            dismissDialog()
            showFailDialog(getString(R.string.scan_fail))
        }

        scanView?.setOnLightVisibleCallback {
            if (it) btn_flash?.visibility = View.VISIBLE else btn_flash?.visibility = View.GONE
        }

    }

 override fun onStart() {
        super.onStart()
        d("onStart", scanView)
        scanView?.onStart()
    }

    override fun onResume() {
        super.onResume()
        d("onResume")
        scanView?.onResume()
    }

    override fun onPause() {
        super.onPause()
        d("onPause")
        scanView?.onPause()
    }

    override fun onStop() {
        super.onStop()
        scanView?.onStop()
    }

    override fun onDestroy() {
        super.onDestroy()
        scanView?.onDestroy()
    }
`

**Comment by HuaZaiWuDi** [comment]
![image](https://user-images.githubusercontent.com/26106636/117239174-d9da7c00-ae60-11eb-95bf-2c5359b80315.png)

**Comment by HMS-ScanKit** [comment]
未调用RemoteView的onCreate方法初始化

**Comment by HuaZaiWuDi** [comment]
好的，谢谢
