### ISSUE TITLE
上架谷歌市场权限问题

### ISSUE THREAD

**Issue by Qdafengzi** [HMS-Core/hms-scan-demo#24]
你好，如果集成了扫描功能想上架谷歌市场，现在上架对权限要求非常高，如果是android10以上的，不能随便使用SD卡权限，要使用私有存储空间。另一个能否相机和存储权限分开申请。在调用扫码的时候必须两个同时申请。

**Comment by HMS-ScanKit** [comment]
默认提供的扫码页面有打开相册的功能，所以需要同时申请相机和存储权限。如果确实需要分开，建议自定义扫码页面。另外，我们申请了SD卡权限，只是通过Uri来解码图库中的二维码图片，并不需要使用私有存储空间。
