### ISSUE TITLE
二维码具体位置，半径及圆心

### ISSUE THREAD

**Issue by sunxu3074** [HMS-Core/hms-scan-demo#25]
请问能不能出一份HmsScan里getBorderRect函数的具体意义？现在返给我的HmsScan对象里Rect有值2300多，可我整个预览的大小都不超过2000，直接绘制不见了。
期望能出一个函数获取二维码的具体位置、半径及圆心。

**Comment by sunxu3074** [comment]
前提是复用了一下demo里面的ScanResultView，但是在识别二维码后的页面上用的，两个布局的view大小一致。

**Comment by HMS-ScanKit** [comment]
getBorderRect方法的含义是算法侧返回的二维码在图像上的坐标数据。它的数据并不等于View坐标系的值。

**Comment by sunxu3074** [comment]
> getBorderRect方法的含义是算法侧返回的二维码在图像上的坐标数据。它的数据并不等于View坐标系的值。

getBorderRect返回的是Rect(1956, 1389 - 2458, 1902)，图片的分辨率是4000x2250，这个rect代表的意义是getLeft，getTop，getRight, getBottom的分辨率值？我算了一下还是对应不上二维码的位置。

**Comment by HMS-ScanKit** [comment]
getLeft,getTop返回的是距离左边，距离顶部的像素值。
1.首先是相机的预览角度问题，我们的default跟custom有对帧数据进行旋转处理。而bitmap接口以及多码接口没有处理，如果是这种情况，可以参考下demo。
2.default跟custom都对帧数据旋转过，这种情况下，getLeft，getTop对应的是与预览方向一致的数值。以default为例，left的值加上rect剪裁的值之和除以1080(top是1920)， 这个比例就等于二维码在实际SurfaceView大小中的比例。default的扫描点就是基于getBorderRect计算而来

**Comment by yinghuayu2377** [comment]
> getLeft,getTop返回的是距离左边，距离顶部的像素值。
> 1.首先是相机的预览角度问题，我们的default跟custom有对帧数据进行旋转处理。而bitmap接口以及多码接口没有处理，如果是这种情况，可以参考下demo。
> 2.default跟custom都对帧数据旋转过，这种情况下，getLeft，getTop对应的是与预览方向一致的数值。以default为例，left的值加上rect剪裁的值之和除以1080(top是1920)， 这个比例就等于二维码在实际SurfaceView大小中的比例。default的扫描点就是基于getBorderRect计算而来

请问这个二维码在图像上的坐标数据和在View坐标系中的值是如何换算的；上边提到left的值加上rect裁剪的值......，这个rect裁剪的值具体是指哪一个数值？

**Comment by HMS-ScanKit** [comment]
没有具体的换算公式，只有逻辑。
rect裁剪的数值是内部的处理规则。

**Comment by yinghuayu2377** [comment]
> 没有具体的换算公式，只有逻辑。
> rect裁剪的数值是内部的处理规则。

那在实际开发过程中，我们就无法精确画出扫描中心点在view上的位置了？

**Comment by HMS-ScanKit** [comment]
是的
