### ISSUE TITLE
非华为手机无法识别相册中的条形码

### ISSUE THREAD

**Issue by xkkk** [HMS-Core/hms-scan-demo#31]
Default View Model
问题：点击右上角的图片进入相册，华为手机可以正常识别二维码和条形码。非华为手机只能识别二维码，无法识别条形码。
请问应该怎样配置才能识别条形码？

**Comment by Mike-mei** [comment]
建议换成SDK-Plus试一下，参考[文档](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples-V5/android-sample-code-0000001050734383-V5#ZH-CN_TOPIC_0000001050734383__section49171561518)

**Comment by xkkk** [comment]
> 建议换成SDK-Plus试一下，参考[文档](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples-V5/android-sample-code-0000001050734383-V5#ZH-CN_TOPIC_0000001050734383__section49171561518)
谢谢 我下载github 的代码 发现使用plus除了Default View Model 其他都可以。但是我将自己项目中的com.huawei.hms:scan:1.3.1.300 升级为 com.huawei.hms:scanplus:1.3.1.300 却又识别不了而且和demo的速度差很多。请问这是什么原因？

**Comment by Mike-mei** [comment]
Scan SDK和SDK-plus是有区别的，详细可参考[文档](https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Guides-V5/android-integrating-sdk-0000001050042006-V5)
两者的主要差异是SDK-plus自带增强识别模型，针对非华为有更好的识别效果，SDK随着版本迭代也在不断优化识别效果，您可以使用最新的SDK版本：'com.huawei.hms:scanplus:1.3.2.300'
