### ISSUE TITLE
camera1已经废弃，建议迁移到camera2

### ISSUE THREAD

**Issue by ZWN2001** [HMS-Core/hms-scan-demo#52]
https://developer.android.com/reference/android/hardware/camera2/package-summary

**Comment by Xuejiao-Shi** [comment]
您好，感谢您的反馈，由于camera2支持的最低版本较高(最低是Android 21)，因此暂时不会迁camera2。

**Comment by ZWN2001** [comment]
sorry忘记关issue，不过cameraX兼容性不错，也可以考虑
