### ISSUE TITLE
摄像头角度问题

### ISSUE THREAD

**Issue by gengsonghang** [HMS-Core/hms-scan-demo#57]
在智能硬件上，默认是横屏模式，没有重力感应，使用demo摄像头预览角度旋转了90度，这个可以调整吗？

**Comment by Xuejiao-Shi** [comment]
您好，为了更好的定位这个问题，麻烦提供以下信息：1.具体的设备型号；2.记录发生此问题的录屏；3.具体使用的扫码模式？

**Comment by gengsonghang** [comment]
是否可以提供邮箱，我把录屏发过去，硬件还未上市，无论哪种扫码方向都不对

**Comment by Xuejiao-Shi** [comment]
@gengsonghang 您可以发到hmscore@huawei.com这个邮箱，附上GitHub的issue链接~

**Comment by gengsonghang** [comment]
已发邮件

**Comment by gengsonghang** [comment]
这个角度问题有解决方法吗

**Comment by Xuejiao-Shi** [comment]
您好，您可以在示例代码中修改下图参数，再尝试Bitmap Mode,MultiProcessor Mode扫码。

![image](https://user-images.githubusercontent.com/99166105/165465950-1dcf4b47-391c-499c-ad5c-6c03f61dd682.png)
