### ISSUE TITLE
小米相册选码无法触发onActivityResult回掉

### ISSUE THREAD

**Issue by congmf** [HMS-Core/hms-scan-demo#59]
在小米12Pro中，MIUI 13.0.30，使用default view方式打开扫码，点击右上角“相册”，小米上会弹出“相册”和“文件管理”，选择相册，选码后无法触发onActivityResult回掉

**Comment by Xuejiao-Shi** [comment]
您好，方便提供一个录屏么，可以发送到hmscore@huawei.com邮箱，附上issue链接

**Comment by congmf** [comment]
搞了个乌龙，真实原因是由于配置了扫码页singleInstance导致result_code=0，没有解析到
