### ISSUE TITLE
开发者您好，想请问扫码默认界面扫码成功后，可否不退出？

### ISSUE THREAD

**Issue by tnngo** [HMS-Core/hms-scan-demo#66]
我是一名后端开发，是位刚上手Android开发的小白，刚接手Android一个临时任务的APP。想请问一下默认界面扫码成功后，可否不用退出？我的场景是仓库管理员，需要连续扫码，直接在扫码界面得到结果。但由于我是后端，如果用自定义界面就画不出默认界面那样酷炫的效果。
如果现在没有这功能，以后会不会考虑增加？比如增加一个回调方法，让开发者自己实现对结果的处理，比如我在回调里直接使用Toast展示结果。

**Comment by Xuejiao-Shi** [comment]
您好，根据您的场景建议您尝试下MultiProcessor扫码模式，请下载SDK测试MultiProcessor扫码的效果。示例代码链接:https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples/android-sample-code-0000001050734383

**Comment by tnngo** [comment]
> 您好，根据您的场景建议您尝试下MultiProcessor扫码模式，请下载SDK测试MultiProcessor扫码的效果。示例代码链接:https://developer.huawei.com/consumer/cn/doc/development/HMSCore-Examples/android-sample-code-0000001050734383

好的谢谢，看样子也只能暂时这样了，其实我更需要的是默认界面的酷炫效果。
