### ISSUE TITLE
使用Bitmap Mode模式的话 有对光线暗的监听回调吗 以及控制闪光灯的开关

### ISSUE THREAD

**Issue by liwei49699** [HMS-Core/hms-scan-demo#69]

**Comment by Xuejiao-Shi** [comment]
您好，您可以参考这个链接：https://blog.csdn.net/PRIMEZPY/article/details/78628030?spm=1001.2014.3001.5506

**Comment by liwei49699** [comment]
哦 好的 我看default 或者customer里有这个的api 

使用customer的时候 怎么暂停相机预览啊  remoteView.pauseContinuouslyScan()  这个只能暂停识别

**Comment by Xuejiao-Shi** [comment]
您好，如不想展示预览界面可以调RemoteView的生命周期看下效果，是不是您要的onDestroy，onPause，onResume，onStop。
参考文档：https://developer.huawei.com/consumer/cn/doc/development/HMSCore-References/scan-remoteview4-0000001050167711

**Comment by liwei49699** [comment]
我要在扫描界面显示信息弹框 我想在这个时候暂停预览 但是调用remoteView.onPause以及remoteView.pauseContinuouslyScan() 预览页面都没有停止
Bitmap Mode里的surfaceHolder!!.removeCallback(surfaceCallBack)这样可以

**Comment by liwei49699** [comment]
好的 remoteView.onStop()是可以的
