### ISSUE TITLE
添加防混淆配置文件后 上架google play aab的体积比release apk大3MB左右

### ISSUE THREAD

**Issue by liwei49699** [HMS-Core/hms-scan-demo#71]
-ignorewarnings
-keepattributes *Annotation*
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable

-keep class com.huawei.hianalytics.**{*;}
-keep class com.huawei.updatesdk.**{*;}
-keep class com.huawei.hms.**{*;}
上面的几个配置是必须的吗 这样会导致aab 体积增大

**Comment by liwei49699** [comment]
![image](https://user-images.githubusercontent.com/26686883/186347518-66f37c6a-12c9-43c2-8b9d-17caf0d9ef8d.png)
主要是这个文件增加了2M多

**Comment by Xuejiao-Shi** [comment]
您好，需要添加混淆，不配置混淆可能会出现找不到类等错误。

**Comment by liwei49699** [comment]
-keep class com.huawei.hianalytics.{*;}
-keep class com.huawei.updatesdk.{;}
-keep class com.huawei.hms.**{;}
这些应该是必须的吧
-ignorewarnings
-keepattributes Annotation
-keepattributes Exceptions
-keepattributes InnerClasses
-keepattributes Signature
-keepattributes SourceFile,LineNumberTable
这些也是必须的吗 
奇怪的是打的aab 比 已添加防混淆配置的release apk 要再大3M 就是引入后大了6M
然后就是mapping从3.5M变成了25M
