### ISSUE TITLE
bugly 上报java.lang.RuntimeException

### ISSUE THREAD

**Issue by liwei49699** [HMS-Core/hms-scan-demo#72]
https://developer.huawei.com/consumer/cn/forum/topic/0202961207784020042?fid=18
如链接
使用的是：scanplus:2.6.0.301 崩溃 .使用mode: customized View 我线上也有此问题 
#2581155 java.lang.RuntimeException
Camera is being used after Camera.release() was called
android.hardware.Camera.setHasPreviewCallback(Native Method)
请问这个问题的进度怎么样了

**Comment by Xuejiao-Shi** [comment]
问题已经在2.7.0.301版本修复，您可以集成2.7.0.301试一下

**Comment by liwei49699** [comment]
好的 官网的版本更新说明是没更新吗

**Comment by liwei49699** [comment]
scanplus:2.7.0.301  下载不下来 我没有使用插件 只是配置了华为maven 仓库 
2.6.0.301是可以的
![image](https://user-images.githubusercontent.com/26686883/186568481-d9f1cfc0-93ec-43f3-9789-9abf4be6dbe5.png)

**Comment by Xuejiao-Shi** [comment]
您好，很抱歉2.7.0.301还属于调测阶段未正式发布，您反馈的问题我们会在月底前发一个补丁包出来解决。

**Comment by liwei49699** [comment]
好的 谢谢
