### ISSUE TITLE
Customized View Mode的方式集成到react native的ViewManager中当react native组件使用时黑屏

### ISSUE THREAD

**Issue by OneHangH** [HMS-Core/hms-scan-demo#82]
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/31791685/205209480-0e80607d-df44-4a76-b121-03df48abb947.png">

**Comment by OneHangH** [comment]
相机权限已提前获取且hardwareAccelerated="true"

**Comment by OneHangH** [comment]
<img width="1780" alt="image" src="https://user-images.githubusercontent.com/31791685/205209798-da45b439-4177-40c5-858d-7a871a690c7f.png">

**Comment by xuxiapu** [comment]
@OneHangH 尊敬的开发者您好，
麻烦提供下您的SDK版本和相关效果录屏，以便于我们更好地定位问题。

**Comment by OneHangH** [comment]
> @OneHangH 尊敬的开发者您好， 麻烦提供下您的SDK版本和相关效果录屏，以便于我们更好地定位问题。

android targetSdkVersion = 30

implementation 'com.huawei.hms:scan:2.8.0.300'

相关效果就是打开组件整个屏幕是黑的

**Comment by xuxiapu** [comment]
@OneHangH 您好，麻烦再提供一下APK，我们将进一步定位问题所在。

**Comment by OneHangH** [comment]
> @OneHangH 您好，麻烦再提供一下APK，我们将进一步定位问题所在。

问题解决了，这边fork改了react-native-camear的源码，用了hms scan 的 HmsScanAnalyzer 去改造处理条形码识别部分，识别率准确率妥妥的。感谢
